config/routes.rb
Livraria::Application.routes.draw do
  resources :produtos

end

app/models/produto.rb
class Produto < ActiveRecord::Base
  validates :nome, :quantidade, :preco, presence: true
  validates :quantidade, numericality: {
    greater_than: 0, only_integer: true }
  validates :preco, numericality: {
    greater_than_or_equal_to: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render action: 'show', status: :created, location: @produto }
      else
        format.html { render action: 'new' }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :preco, :quantidade)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Livraria</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/produtos/_form.html.erb
<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :preco, 'Preço' %><br>
    <%= f.text_field :preco %>
  </div>
  <div class="field">
    <%= f.label :quantidade %><br>
    <%= f.number_field :quantidade %>
  </div>
  <div class="actions">
    <%= f.submit 'Salvar' %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editing produto</h1>

<%= render 'form' %>

<%= link_to 'Show', @produto %> |
<%= link_to 'Back', produtos_path %>

app/views/produtos/index.html.erb
<h1>Listing produtos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Preco</th>
      <th>Quantidade</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.nome %></td>
        <td><%= produto.preco %></td>
        <td><%= produto.quantidade %></td>
        <td><%= link_to 'Show', produto %></td>
        <td><%= link_to 'Edit', edit_produto_path(produto) %></td>
        <td><%= link_to 'Destroy', produto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produto', new_produto_path %>

app/views/produtos/new.html.erb
<h1>New produto</h1>

<%= render 'form' %>

<%= link_to 'Back', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Preço:</strong>
  <%= number_to_currency(@produto.preco,
        unit: 'R$ ', separator: ',', delimiter: '.') %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @produto.quantidade %>
</p>

<%= link_to 'Edit', edit_produto_path(@produto) %> |
<%= link_to 'Back', produtos_path %>